version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '${FORWARD_APP_PORT}:80'
        volumes:
            - ./backend:/var/www/backend
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - parspack
        working_dir: /var/www/
    backend:
        image: backend/parspack
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/var/www/backend
        networks:
            - parspack
        working_dir: /var/www/backend
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - parspack
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    parspack:
        driver: bridge
volumes:
    mysql:
        driver: local